### ISSUE TITLE
gaxios throw error in onSync of `requestsync` endpoint

### ISSUE THREAD

**Issue by unsigned6** [googlecodelabs/smarthome-local#14]
I've deployed to firebase on step 3, but see a web interface with no device.
Viewing logs of `requestsync` in firebase see next:

```
requestsync
{ Error: Requested entity was not found.
    at Gaxios._request (/workspace/node_modules/googleapis/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   { config:
      { url: 'https://homegraph.googleapis.com/v1/devices:requestSync',
        method: 'POST',...
```

Any ideas ho to solve this?

**Comment by Michael-Hanley** [comment]
Receiving the same issue
