### ISSUE TITLE
cannot deploy function (TypeError: instance.INTERNAL.registerComponent is not a function)

### ISSUE THREAD

**Issue by chadstick** [googlecodelabs/smarthome-local#6]
Getting this error when I try to deploy:

TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (C:\Users\chad_\sh\app-start\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15393:39)
    at Object.<anonymous> (C:\Users\chad_\sh\app-start\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15426:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at FirebaseNamespace.get [as database] (C:\Users\chad_\sh\app-start\functions\node_modules\firebase-admin\lib\firebase-namespace.js:282:38)

**Comment by Fleker** [comment]
Can you try [installing @firebase/app](https://github.com/firebase/firebase-admin-node/issues/722#issuecomment-567427306) in your functions directory?

`npm install @firebase/app --save`

**Comment by chadstick** [comment]
Yup, that worked. Thanks again Nick!
